from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
import os
import tempfile
from datetime import datetime


# -- Color palette -------------------------------------------------------------
COLOR_BLACK      = colors.HexColor("#1a1a18")
COLOR_RED        = colors.HexColor("#dc2626")
COLOR_ORANGE     = colors.HexColor("#d97706")
COLOR_GREEN      = colors.HexColor("#16a34a")
COLOR_LIGHT_GRAY = colors.HexColor("#f8f7f4")
COLOR_BORDER     = colors.HexColor("#e0dedd")
COLOR_GEMINI     = colors.HexColor("#4285F4")   # Google blue for footer


def _score_color(score: int):
    """Returns a reportlab color based on how biased the system is."""
    if score < 50:
        return COLOR_RED
    elif score < 75:
        return COLOR_ORANGE
    else:
        return COLOR_GREEN


def _score_label(score: int) -> str:
    if score < 50:
        return "CRITICAL -- IMMEDIATE ACTION REQUIRED"
    elif score < 75:
        return "WARNING -- REMEDIATION RECOMMENDED"
    else:
        return "HEALTHY -- NO ACTION REQUIRED"


# -- TXT fallback --------------------------------------------------------------
def _generate_txt_fallback(audit_id: str, result: dict) -> str:
    path = os.path.join(tempfile.gettempdir(), f"fairscan_{audit_id[:8]}.txt")

    score     = result.get("fairness_score", 0)
    memo      = result.get("report", {}).get("memo", "No memo generated.")
    violations = result.get("legal", {}).get("violations", [])
    date_str  = datetime.now().strftime("%B %d, %Y")

    lines = [
        "=" * 60,
        "FAIRSCAN -- AI BIAS AUDIT REPORT",
        f"Model: {result.get('model_name', 'Unknown')}",
        f"Audit ID: {audit_id[:8]}",
        f"Date: {date_str}",
        "=" * 60,
        "",
        f"FAIRNESS SCORE: {score}/100  [{_score_label(score)}]",
        "",
        "-" * 60,
        memo,
        "",
        "-" * 60,
        "REGULATORY FINDINGS",
        "-" * 60,
    ]

    for v in violations:
        lines.append(f"[{v.get('risk_level','').upper()}] {v.get('regulation','')}")
        lines.append(f"  Finding: {v.get('finding','')}")
        lines.append(f"  Action:  {v.get('required_action','')}")
        lines.append(f"  Deadline:{v.get('deadline','')}")
        lines.append("")

    lines += [
        "=" * 60,
        "Powered by Google Gemini | FairScan",
        "=" * 60,
    ]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    return path


# -- Add footer to every page --------------------------------------------------
def _make_page_footer(canvas, doc):
    """Called by ReportLab on every page -- draws the footer."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(COLOR_GEMINI)
    date_str = datetime.now().strftime("%B %d, %Y")
    canvas.drawCentredString(
        A4[0] / 2,
        1.2 * cm,
        f"Generated by FairScan  |  Powered by Google Gemini  |  {date_str}"
    )
    canvas.setFillColor(COLOR_BORDER)
    canvas.line(2 * cm, 1.5 * cm, A4[0] - 2 * cm, 1.5 * cm)
    canvas.restoreState()


# -- Main function -------------------------------------------------------------
def generate_pdf(audit_id: str, result: dict) -> str:
    """
    Builds a professional compliance PDF report.
    Returns the file path so main.py can serve it as a download.
    Falls back to a .txt file if ReportLab crashes.
    """
    pdf_path = os.path.join(tempfile.gettempdir(), f"fairscan_{audit_id[:8]}.pdf")

    try:
        _build_pdf(pdf_path, audit_id, result)
        print(f"[PDF] Generated successfully at {pdf_path}")
        return pdf_path

    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"[PDF] ReportLab error: {e} -- falling back to .txt")
        return _generate_txt_fallback(audit_id, result)


def _build_pdf(path: str, audit_id: str, result: dict):
    """Does the actual ReportLab work. Separated so generate_pdf can catch errors."""

    doc = SimpleDocTemplate(
        path,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "Title",
        parent=styles["h1"],
        fontSize=22,
        textColor=COLOR_BLACK,
        spaceAfter=4,
        fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#555555"),
        spaceAfter=2,
    )
    section_style = ParagraphStyle(
        "Section",
        parent=styles["h2"],
        fontSize=13,
        textColor=COLOR_BLACK,
        spaceBefore=14,
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        textColor=COLOR_BLACK,
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        parent=body_style,
        leftIndent=16,
        spaceAfter=4,
    )

    # Pull data from result object
    score       = result.get("fairness_score", 0)
    model_name  = result.get("model_name", "Unknown Model")
    date_str    = datetime.now().strftime("%B %d, %Y")
    memo        = result.get("report", {}).get("memo", "No report generated.")
    violations  = result.get("legal", {}).get("violations", [])

    story = []

    # -- 1. HEADER --------------------------------------------------------------
    header_table = Table(
        [[
            [
                Paragraph("FairScan", title_style),
                Paragraph("AI BIAS AUDIT REPORT", subtitle_style),
            ],
            [
                Paragraph(f"<b>{model_name}</b>", ParagraphStyle("HdrR", parent=subtitle_style, alignment=2, textColor=COLOR_BLACK, fontSize=11)),
                Paragraph(f"Generated: {date_str}", ParagraphStyle("HdrR2", parent=subtitle_style, alignment=2)),
                Paragraph(f"Dataset: {result.get('stat', {}).get('row_count', 'Unknown')} rows",
                          ParagraphStyle("HdrR3", parent=subtitle_style, alignment=2)),
                Paragraph(f"Audit ID: {audit_id[:8]}", ParagraphStyle("HdrR4", parent=subtitle_style, alignment=2)),
            ]
        ]],
        colWidths=[8 * cm, 8.5 * cm]
    )
    story.append(header_table)
    story.append(HRFlowable(width="100%", thickness=1, color=COLOR_BORDER, spaceBefore=4, spaceAfter=20))

    # -- 2. FAIRNESS SCORE BANNER -----------------------------------------------
    banner_color = _score_color(score)
    banner_label = _score_label(score)

    score_table = Table(
        [[
            Paragraph(
                f'<font color="{banner_color.hexval()}"><b>{score}</b></font><font color="#cccccc" size="14">/100</font>',
                ParagraphStyle("ScoreNum", fontSize=48, fontName="Helvetica-Bold", alignment=1, leading=52)
            ),
            [
                Paragraph(f'<b>{banner_label}</b>',
                          ParagraphStyle("ScoreLabel", fontSize=14, fontName="Helvetica-Bold", leading=20, textColor=banner_color)),
                Paragraph(f"{len(violations)} regulatory violations found. {len(result.get('sensitive_columns', []))} sensitive columns analysed.",
                          ParagraphStyle("ScoreDesc", fontSize=10, leading=14, textColor=colors.HexColor("#666666"), spaceBefore=4))
            ]
        ]],
        colWidths=[5.5 * cm, 11 * cm]
    )
    score_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), colors.white),
        ("BOX",           (0, 0), (-1, -1), 1, COLOR_BORDER),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 20),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 20),
        ("LEFTPADDING",   (0, 0), (-1, -1), 20),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 20),
        ("ROUNDEDCORNERS", [8]),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 0.4 * cm))

    # -- 2b. METHODOLOGY & METRICS ----------------------------------------------
    methodology_data = [
        [Paragraph("<b>Methodology & Metrics</b>", ParagraphStyle("MethHead", parent=body_style, fontName="Helvetica-Bold", textColor=COLOR_BLACK))]
    ]
    
    meth_body = f"""
    <b>Method:</b> Adverse Impact Ratio (EEOC 4/5ths Rule)<br/>
    <b>Formula:</b> <font face="Courier">min(group_approval_rate) / max(group_approval_rate) × 100</font><br/>
    <b>Interpretation:</b> Score below 80 = legally significant adverse impact under US law.<br/><br/>
    <b>Supporting Fairlearn Metrics:</b><br/>
    """
    
    for col, data in list(result.get("stat", {}).get("results_per_group", {}).items())[:2]:
        dp = data.get("demographic_parity_difference", "N/A")
        eo = data.get("equalized_odds_difference", "N/A")
        meth_body += f"&bull; <b>{col.capitalize()}</b> - DP Diff: {dp} | EO Diff: {eo}<br/>"

    methodology_data.append([Paragraph(meth_body, ParagraphStyle("MethBody", parent=body_style, leading=14))])
    
    meth_table = Table(methodology_data, colWidths=[16.5 * cm])
    meth_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), COLOR_LIGHT_GRAY),
        ("BOX",           (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
        ("ROUNDEDCORNERS", [4]),
    ]))
    story.append(meth_table)
    story.append(Spacer(1, 0.6 * cm))

    # -- 3. EXECUTIVE SUMMARY ---------------------------------------------------
    story.append(Paragraph("Executive Summary", section_style))

    memo_lines = memo.split("\n")
    in_exec_summary = False
    exec_lines = []

    for line in memo_lines:
        stripped = line.strip().replace("**", "")
        if stripped.upper().startswith("EXECUTIVE SUMMARY"):
            in_exec_summary = True
            after_colon = stripped.split(":", 1)[-1].strip()
            if after_colon:
                exec_lines.append(after_colon)
        elif in_exec_summary:
            if any(stripped.upper().startswith(k) for k in
                   ["METHODOLOGY", "KEY FINDINGS", "ROOT CAUSE", "REQUIRED ACTIONS", "RISK IF IGNORED"]):
                break
            if stripped:
                exec_lines.append(stripped)

    if not exec_lines:
        exec_lines = [l.strip() for l in memo_lines if l.strip()][:2]

    for line in exec_lines:
        story.append(Paragraph(line, body_style))
        story.append(Spacer(1, 0.15 * cm))

    # -- 3.5 METHODOLOGY --------------------------------------------------------
    in_methodology_sec = False
    methodology_lines = []
    for line in memo_lines:
        stripped = line.strip().replace("**", "")
        if stripped.upper().startswith("METHODOLOGY"):
            in_methodology_sec = True
            after_colon = stripped.split(":", 1)[-1].strip()
            if after_colon:
                methodology_lines.append(after_colon)
        elif in_methodology_sec:
            if any(stripped.upper().startswith(k) for k in
                   ["KEY FINDINGS", "ROOT CAUSE", "REQUIRED ACTIONS", "RISK IF IGNORED"]):
                break
            if stripped:
                methodology_lines.append(stripped)

    if methodology_lines:
        story.append(Paragraph("Methodology", section_style))
        for line in methodology_lines:
            if ":" in line:
                parts = line.split(":", 1)
                clean_line = f"<b><font color='{COLOR_RED.hexval()}'>{parts[0]}:</font></b>{parts[1]}"
                if line.startswith("* ") or line.startswith("• "):
                    # Remove the original bullet so we can style our own
                    clean_line = clean_line.replace("* ", "", 1).replace("• ", "", 1)
                    story.append(Paragraph(f'<font color="{COLOR_RED.hexval()}">&bull;</font> {clean_line}', bullet_style))
                else:
                    story.append(Paragraph(clean_line, body_style))
                    story.append(Spacer(1, 0.1 * cm))
            else:
                if line.startswith("* ") or line.startswith("• "):
                    clean_line = line.lstrip("*• ")
                    story.append(Paragraph(f'<font color="{COLOR_RED.hexval()}">&bull;</font> {clean_line}', bullet_style))
                else:
                    story.append(Paragraph(line, body_style))
                    story.append(Spacer(1, 0.1 * cm))

    # -- 4. KEY FINDINGS (bullet points) ---------------------------------------
    story.append(Paragraph("Key Findings", section_style))

    in_findings = False
    findings_lines = []
    for line in memo_lines:
        stripped = line.strip().replace("**", "")
        if stripped.upper().startswith("KEY FINDINGS"):
            in_findings = True
        elif in_findings:
            if any(stripped.upper().startswith(k) for k in
                   ["ROOT CAUSE", "REQUIRED ACTIONS", "RISK IF IGNORED"]):
                break
            if stripped:
                findings_lines.append(stripped)

    if findings_lines:
        for bullet in findings_lines:
            clean = bullet.lstrip("-•* ").strip()
            story.append(Paragraph(f"&bull; {clean}", bullet_style))
    else:
        story.append(Paragraph(f"&bull; Fairness score: {score}/100", bullet_style))

    story.append(Spacer(1, 0.3 * cm))

    # -- 5. BIAS HEATMAP TABLE --------------------------------------------------
    group_data = result.get("stat", {}).get("results_per_group", {})
    if group_data:
        story.append(Paragraph("Bias Heatmap", section_style))

        for col_name, col_info in group_data.items():
            story.append(Paragraph(f"<b>{col_name.upper()}</b>", ParagraphStyle("ColHeader", parent=body_style, fontName="Helvetica-Bold", spaceBefore=6, spaceAfter=4)))

            groups = col_info.get("groups", {})
            if not groups:
                continue

            max_rate = max(groups.values()) if groups else 0

            heatmap_data = [[
                Paragraph("<b>Group</b>", body_style),
                Paragraph("<b>Approved %</b>", body_style),
                Paragraph("<b>Rejected %</b>", body_style),
                Paragraph("<b>Gap vs Best</b>", body_style),
            ]]

            for grp, rate in groups.items():
                gap_val = round(rate - max_rate, 1)
                gap_text = "baseline" if gap_val == 0 else f"{gap_val}pp"
                gap_color = COLOR_GREEN if gap_val == 0 else (COLOR_RED if gap_val < -10 else COLOR_ORANGE)

                heatmap_data.append([
                    Paragraph(f"<b>{grp}</b>", body_style),
                    Paragraph(f"{rate:.1f}%", body_style),
                    Paragraph(f"{100 - rate:.0f}%", body_style),
                    Paragraph(f'<font color="{gap_color.hexval()}">{gap_text}</font>', body_style),
                ])

            ht = Table(heatmap_data, colWidths=[5 * cm, 4 * cm, 4 * cm, 4 * cm])
            ht.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, 0), COLOR_BLACK),
                ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
                ("FONTSIZE",      (0, 0), (-1, -1), 9),
                ("BACKGROUND",    (0, 1), (-1, -1), COLOR_LIGHT_GRAY),
                ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, COLOR_LIGHT_GRAY]),
                ("GRID",          (0, 0), (-1, -1), 0.5, COLOR_BORDER),
                ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING",    (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ]))
            story.append(ht)
            story.append(Spacer(1, 0.3 * cm))

    # -- 6. ROOT CAUSE SECTION --------------------------------------------------
    root_cause = result.get("root_cause", {})
    if root_cause:
        story.append(Paragraph("Root Cause Analysis", section_style))
        top_driver = root_cause.get("top_bias_driver", "unknown")
        story.append(Paragraph(f'Primary driver: <b><font color="{COLOR_RED.hexval()}">{top_driver}</font></b>', body_style))
        story.append(Spacer(1, 0.2 * cm))

        ranking = root_cause.get("feature_ranking", [])[:5]
        if ranking:
            rc_data = [[
                Paragraph("<b>Feature</b>", body_style),
                Paragraph("<b>SHAP Importance</b>", body_style),
            ]]
            for feat in ranking:
                rc_data.append([
                    Paragraph(feat.get("column", ""), body_style),
                    Paragraph(f"{feat.get('shap_importance', 0):.4f}", body_style),
                ])

            rct = Table(rc_data, colWidths=[10 * cm, 7 * cm])
            rct.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, 0), COLOR_BLACK),
                ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
                ("FONTSIZE",      (0, 0), (-1, -1), 9),
                ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, COLOR_LIGHT_GRAY]),
                ("GRID",          (0, 0), (-1, -1), 0.5, COLOR_BORDER),
                ("TOPPADDING",    (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ]))
            story.append(rct)
        
        explanation = root_cause.get("explanation", "")
        if explanation:
            story.append(Spacer(1, 0.2 * cm))
            story.append(Paragraph(explanation, body_style))

    # -- 7. LEGAL VIOLATIONS TABLE ----------------------------------------------
    if violations:
        story.append(Paragraph("Regulatory Findings", section_style))

        table_data = [[
            Paragraph("<b>Risk</b>", body_style),
            Paragraph("<b>Regulation</b>", body_style),
            Paragraph("<b>Required Action</b>", body_style),
            Paragraph("<b>Deadline</b>", body_style),
        ]]

        for v in violations:
            risk = v.get("risk_level", "low").lower()
            risk_color = {
                "high": COLOR_RED,
                "medium": COLOR_ORANGE,
                "low": COLOR_GREEN
            }.get(risk, COLOR_BLACK)

            table_data.append([
                Paragraph(
                    f'<font color="{risk_color.hexval() if hasattr(risk_color, "hexval") else "#000"}">'
                    f'<b>{risk.upper()}</b></font>',
                    body_style
                ),
                Paragraph(v.get("regulation", ""), body_style),
                Paragraph(v.get("required_action", ""), body_style),
                Paragraph(v.get("deadline", ""), body_style),
            ])

        t = Table(table_data, colWidths=[2.5 * cm, 4 * cm, 7.5 * cm, 3 * cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), COLOR_BLACK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("BACKGROUND",    (0, 1), (-1, -1), COLOR_LIGHT_GRAY),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, COLOR_LIGHT_GRAY]),
            ("GRID",          (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ]))
        story.append(t)

    # -- 8. REQUIRED ACTIONS (numbered list) -----------------------------------
    story.append(Paragraph("Required Actions", section_style))

    in_actions = False
    action_lines = []
    for line in memo_lines:
        stripped = line.strip().replace("**", "")
        if stripped.upper().startswith("REQUIRED ACTIONS"):
            in_actions = True
        elif in_actions:
            if any(stripped.upper().startswith(k) for k in ["RISK IF IGNORED", "EXECUTIVE"]):
                break
            if stripped:
                action_lines.append(stripped)

    if action_lines:
        for i, action in enumerate(action_lines, start=1):
            clean = action.lstrip("0123456789.-) ").strip()
            story.append(Paragraph(f"{i}. {clean}", bullet_style))
    else:
        for i, v in enumerate(violations, start=1):
            story.append(Paragraph(f"{i}. {v.get('required_action', '')}", bullet_style))

    # -- 9. COMPLIANCE MEMO (full text) ----------------------------------------
    story.append(Paragraph("Full Compliance Memo", section_style))
    in_methodology = False
    for line in memo_lines:
        stripped = line.replace("--", "—").replace("**", "").strip()
        if not stripped:
            continue
            
        # Check for headings (e.g. EXECUTIVE SUMMARY:)
        if stripped.endswith(":") and stripped.upper() == stripped:
            in_methodology = (stripped.upper() == "METHODOLOGY:")
            title_cased = " ".join([w.capitalize() for w in stripped[:-1].split()])
            story.append(Spacer(1, 0.3 * cm))
            story.append(Paragraph(f"<b>{title_cased}</b>", ParagraphStyle(
                "MemoHeading", parent=body_style, fontName="Helvetica-Bold", fontSize=11, spaceAfter=4
            )))
            continue
            
        # Bullet points
        if stripped.startswith("* ") or stripped.startswith("• "):
            clean = stripped.lstrip("*• ").strip()
            if in_methodology and ":" in clean:
                parts = clean.split(":", 1)
                clean = f"<b><font color='{COLOR_RED.hexval()}'>{parts[0]}:</font></b>{parts[1]}"
            story.append(Paragraph(f'<font color="{COLOR_RED.hexval()}">&bull;</font> {clean}', bullet_style))
            continue
            
        # Numbered list
        import re
        num_match = re.match(r"^(\d+\.)\s(.*)", stripped)
        if num_match:
            story.append(Paragraph(f"<b>{num_match.group(1)}</b> {num_match.group(2)}", bullet_style))
            continue

        # Regular text
        if in_methodology and ":" in stripped:
            parts = stripped.split(":", 1)
            formatted_text = f"<b><font color='{COLOR_RED.hexval()}'>{parts[0]}:</font></b>{parts[1]}"
            story.append(Paragraph(formatted_text, body_style))
            story.append(Spacer(1, 0.1 * cm))
            continue

        story.append(Paragraph(stripped, body_style))
        story.append(Spacer(1, 0.1 * cm))

    # -- 10. RISK IF IGNORED ---------------------------------------------------
    in_risk = False
    risk_lines = []
    for line in memo_lines:
        stripped = line.strip().replace("**", "")
        if stripped.upper().startswith("RISK IF IGNORED"):
            in_risk = True
            after = stripped.split(":", 1)[-1].strip()
            if after:
                risk_lines.append(after)
        elif in_risk and stripped:
            risk_lines.append(stripped)
            break

    if risk_lines:
        story.append(Spacer(1, 0.3 * cm))
        risk_box = Table(
            [[Paragraph(f"<b>Risk if ignored:</b> {' '.join(risk_lines)}", body_style)]],
            colWidths=[17 * cm]
        )
        risk_box.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#fff7ed")),
            ("BOX",           (0, 0), (-1, -1), 1, COLOR_ORANGE),
            ("TOPPADDING",    (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ]))
        story.append(risk_box)

    # -- Build the doc (footer is added via onPage callback) -------------------
    doc.build(story, onFirstPage=_make_page_footer, onLaterPages=_make_page_footer)